var styleCodes = [
  {"style_code":65,"style_name":"001 Applique","pcs_per_carrier":16,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":83,"style_name":"001 Coupe L2","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":33,"style_name":"001 Coupe L3","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":23,"style_name":"001 Front L3","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":38,"style_name":"001 Front L4 Extension","pcs_per_carrier":9,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":40,"style_name":"001 L4 Rear Extension","pcs_per_carrier":9,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":63,"style_name":"001 Pontiac Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":62,"style_name":"001 Pontiac Rear Extension","pcs_per_carrier":9,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":35,"style_name":"001 Sedan L2","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":51,"style_name":"001 Sedan L3","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":181,"style_name":"_071_Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":174,"style_name":"_071_Rear_Sport","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":66,"style_name":"071 Base Front 3pc","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":180,"style_name":"071 Front 5 pc","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":71,"style_name":"071 Front Sport","pcs_per_carrier":3,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":3,"style_name":"130 Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":115,"style_name":"130 Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":116,"style_name":"160 Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":6,"style_name":"160 Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":7,"style_name":"178 Front","pcs_per_carrier":3,"customer":"Honda","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":11,"style_name":"178 Rear","pcs_per_carrier":5,"customer":"Honda","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":48,"style_name":"178 THC","pcs_per_carrier":60,"customer":"Honda","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":41,"style_name":"2003 Saturn Front","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":36,"style_name":"2003 Saturn Sedan Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":42,"style_name":"2003 Saturn Wagon Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":146,"style_name":"_206_Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":151,"style_name":"_206_Rocker","pcs_per_carrier":8,"customer":"GM","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":147,"style_name":"_226_Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":142,"style_name":"_226_Rocker","pcs_per_carrier":6,"customer":"GM","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":141,"style_name":"_226V_Rocker","pcs_per_carrier":6,"customer":"GM","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":190,"style_name":"226V Rear Lower","pcs_per_carrier":18,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":19,"style_name":"_230_231_Rocker_LH","pcs_per_carrier":9,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":26,"style_name":"_230_231_Rocker_RH","pcs_per_carrier":9,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":18,"style_name":"230 Front Extension","pcs_per_carrier":9,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":24,"style_name":"230 Rear Extension","pcs_per_carrier":9,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":72,"style_name":"231 Front Extension","pcs_per_carrier":9,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":73,"style_name":"231 Rear Extension","pcs_per_carrier":9,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":67,"style_name":"265 Rear","pcs_per_carrier":6,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":132,"style_name":"295 Fog Lamp","pcs_per_carrier":20,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":60,"style_name":"295V Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":59,"style_name":"295V Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":28,"style_name":"320 Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":31,"style_name":"320 Grill","pcs_per_carrier":12,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":39,"style_name":"320 V Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":37,"style_name":"320V Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":79,"style_name":"_322_Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":85,"style_name":"_322_Rear","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":152,"style_name":"_322_Rocker","pcs_per_carrier":8,"customer":"GM","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":105,"style_name":"322V Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":27,"style_name":"322V Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":133,"style_name":"351 Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":134,"style_name":"_351_Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":158,"style_name":"351MCE Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":183,"style_name":"360 Front Saab","pcs_per_carrier":5,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":179,"style_name":"360 Rear Base","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":182,"style_name":"360 SS Dealer Kit","pcs_per_carrier":12,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":1,"style_name":"425 Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":2,"style_name":"425 Rear","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":5,"style_name":"820 Denali Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":4,"style_name":"820 Denali Rear","pcs_per_carrier":8,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":52,"style_name":"820 LPC","pcs_per_carrier":32,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":50,"style_name":"820C Escalade Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":163,"style_name":"912 Top Cap","pcs_per_carrier":6,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":160,"style_name":"966 Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":150,"style_name":"967 Front Lower","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":155,"style_name":"967 Front Upper","pcs_per_carrier":6,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":125,"style_name":"_967_Hitch_Cover","pcs_per_carrier":24,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":175,"style_name":"967 Hitch Cover Flat","pcs_per_carrier":32,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":81,"style_name":"967 Rear Lower","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":170,"style_name":"967 RR Upper LH","pcs_per_carrier":8,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":171,"style_name":"967 RR Upper RH","pcs_per_carrier":8,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":null,"style_name":"968 Denali Front Lower","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":111,"style_name":"968 Denali Hitch Cover","pcs_per_carrier":20,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":169,"style_name":"968 Denali Rear Lower","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":84,"style_name":"968 Front Upper","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":130,"style_name":"968 RR Upper LH","pcs_per_carrier":8,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":131,"style_name":"968 RR Upper RH","pcs_per_carrier":8,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":107,"style_name":"Alpha Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":57,"style_name":"BMWFront","pcs_per_carrier":4,"customer":"BMW","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":58,"style_name":"BMWRear","pcs_per_carrier":4,"customer":"BMW","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":226,"style_name":"D1BL Converj Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":232,"style_name":"D1BL Converj Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":228,"style_name":"D1BL Converj Rocker LH","pcs_per_carrier":6,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":229,"style_name":"D1BL Converj Rocker RH","pcs_per_carrier":6,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":186,"style_name":"D1SC Front Base 4pc","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":238,"style_name":"D1SC Front Base 5pc","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":187,"style_name":"D1SC Front Sport","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":46,"style_name":"DR SLT","pcs_per_carrier":9,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":44,"style_name":"DRSport","pcs_per_carrier":3,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":140,"style_name":"GM_272_Rocker","pcs_per_carrier":11,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":34,"style_name":"GM001Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":25,"style_name":"GM220Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":8,"style_name":"GM220Rear","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":70,"style_name":"GM222Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":108,"style_name":"GM222Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":68,"style_name":"GM265Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":10,"style_name":"GM270Front","pcs_per_carrier":5,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":20,"style_name":"GM270LPC","pcs_per_carrier":45,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":12,"style_name":"GM270Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":30,"style_name":"GM272Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":32,"style_name":"GM272Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":82,"style_name":"GM295Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":97,"style_name":"GM295Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":29,"style_name":"GM320Rear","pcs_per_carrier":5,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":188,"style_name":"GM360Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":177,"style_name":"GM360Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":999,"style_name":"H Frame","pcs_per_carrier":0,"customer":"-","assembly_flow":"-","color_change_program":"No Data"},
  {"style_code":17,"style_name":"Honda148Front","pcs_per_carrier":4,"customer":"Honda","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":164,"style_name":"KK Door LH","pcs_per_carrier":18,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":161,"style_name":"KK Door RH","pcs_per_carrier":18,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":157,"style_name":"KK Front","pcs_per_carrier":4,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":154,"style_name":"KK Front LH","pcs_per_carrier":7,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":153,"style_name":"KK Front RH","pcs_per_carrier":7,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":165,"style_name":"KK Qtr LH","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":162,"style_name":"KK Qtr RH","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":78,"style_name":"KK_Rear","pcs_per_carrier":4,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":191,"style_name":"Mercedes Front","pcs_per_carrier":14,"customer":"Mercedes","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":192,"style_name":"Mercedes Rear","pcs_per_carrier":10,"customer":"Mercedes","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":45,"style_name":"Mustang Hood Scoop","pcs_per_carrier":16,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":49,"style_name":"Old 295 Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":14,"style_name":"Old Saturn Front","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":15,"style_name":"Old Saturn Rear Masked","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":76,"style_name":"Old_WK_Front_3pc","pcs_per_carrier":3,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":47,"style_name":"Old295Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":103,"style_name":"Opel Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":102,"style_name":"Opel Outers LH & RH","pcs_per_carrier":20,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":104,"style_name":"Opel_Rear","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":144,"style_name":"P415 LH","pcs_per_carrier":16,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":143,"style_name":"P415 RH","pcs_per_carrier":16,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":98,"style_name":"Pin Tracker","pcs_per_carrier":0,"customer":"-","assembly_flow":"-","color_change_program":"Service"},
  {"style_code":13,"style_name":"Saturn Applique","pcs_per_carrier":8,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":166,"style_name":"SRT14_Front_Upper","pcs_per_carrier":3,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":176,"style_name":"SRT8 Fog Bezel LH&RH","pcs_per_carrier":28,"customer":"Chrysler","assembly_flow":"130 Area warehouse","color_change_program":"Service"},
  {"style_code":86,"style_name":"SRT8 Lower Surround","pcs_per_carrier":9,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":145,"style_name":"SRT8_Front_Upper_Old","pcs_per_carrier":3,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":118,"style_name":"T300 Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":110,"style_name":"T300 Notchback 4pc","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":139,"style_name":"T300 Rear Hatchback","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":55,"style_name":"T300 RS Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":56,"style_name":"T300 RS Rear Hatchback","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":80,"style_name":"Volt_Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":61,"style_name":"Volt_Rear","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":92,"style_name":"WD Front Lower","pcs_per_carrier":6,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":94,"style_name":"WD Front Upper","pcs_per_carrier":4,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":93,"style_name":"WD Rear Lower","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":90,"style_name":"WD14 Rear 5pc Spray Carrier","pcs_per_carrier":4,"customer":"-","assembly_flow":"-","color_change_program":"Service"},
  {"style_code":189,"style_name":"WK14 Front Lower","pcs_per_carrier":6,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":101,"style_name":"WK14 Front Upper","pcs_per_carrier":4,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":149,"style_name":"WK14 Front Upper","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":172,"style_name":"WK14 SRT8 Fog Bezel LH&RH","pcs_per_carrier":14,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":184,"style_name":"WK14 Summit Front Lower","pcs_per_carrier":6,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":135,"style_name":"WK14 Summit Front Upper","pcs_per_carrier":4,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Service"},
  {"style_code":53,"style_name":"WK14 Upper Grille","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"Service"},
  {"style_code":null,"style_name":"Trays","pcs_per_carrier":null,"customer":"","assembly_flow":"","color_change_program":""},
  //{"style_code":style_code,"style_name":"style_name","pcs_per_carrier":pcs_per_carrier,"customer":"customer","assembly_flow":"assembly_flow","color_change_program":""},
  {"style_code":106,"style_name":"322 Chin Splitter-2 Trays","pcs_per_carrier":50,"customer":"GM","assembly_flow":"Load","color_change_program":"Trays"},
  {"style_code":295,"style_name":"HFrame WK16.5 HLW DoorLH/RH2 Tray","pcs_per_carrier":256,"customer":"Chrysler","assembly_flow":"Load","color_change_program":"Trays"},
  {"style_code":96,"style_name":"Hframe_1Tray_KL2","pcs_per_carrier":300,"customer":"Chrysler","assembly_flow":"Load","color_change_program":"Trays"},
  {"style_code":109,"style_name":"Hframe_Small_Part_Trays","pcs_per_carrier":0,"customer":"Mixed","assembly_flow":"Load","color_change_program":"Trays"},
  {"style_code":null,"style_name":"Production","pcs_per_carrier":null,"customer":"","assembly_flow":"","color_change_program":""},
  //{"style_code":style_code,"style_name":"style_name","pcs_per_carrier":pcs_per_carrier,"customer":"customer","assembly_flow":"assembly_flow","color_change_program":""},
  {"style_code":113,"style_name":"Bolt Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Bolt"},
  {"style_code":114,"style_name":"Bolt Rear","pcs_per_carrier":5,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Bolt"},
  {"style_code":243,"style_name":"D2JCI Front","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Hercules","color_change_program":"D2JCI"},
  {"style_code":244,"style_name":"D2JCI Rear Upper","pcs_per_carrier":5,"customer":"GM","assembly_flow":"Hercules","color_change_program":"D2JCI"},
  {"style_code":245,"style_name":"D2JCI Rear Lower","pcs_per_carrier":5,"customer":"GM","assembly_flow":"Hercules","color_change_program":"Black"},
  {"style_code":252,"style_name":"D2LC Rear RS","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"D2LC"},
  {"style_code":251,"style_name":"D2LC Rear Base","pcs_per_carrier":3,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"D2LC"},
  {"style_code":311,"style_name":"D2LC Front","pcs_per_carrier":5,"customer":"GM","assembly_flow":"Hercules","color_change_program":"D2LC"},
  {"style_code":255,"style_name":"D2LC Rear Base","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Reindeer","color_change_program":"D2LC"},
  {"style_code":253,"style_name":"D2LC Front - 4 pc.","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Hercules","color_change_program":"D2LC"},
  {"style_code":257,"style_name":"D2LC Rear RS","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Hercules","color_change_program":"D2LC"},
  {"style_code":313,"style_name":"D2LC Rear RS - New 5pc","pcs_per_carrier":5,"customer":"GM","assembly_flow":"Hercules","color_change_program":"D2LC"},
  {"style_code":296,"style_name":"D2LC Front RS - New 5pc","pcs_per_carrier":5,"customer":"GM","assembly_flow":"Hercules","color_change_program":"D2LC"},
  {"style_code":298,"style_name":"D2LC Rear RS - New 5pc","pcs_per_carrier":5,"customer":"GM","assembly_flow":"Hercules","color_change_program":"D2LC"},
  {"style_code":256,"style_name":"D2LC Front RS","pcs_per_carrier":4,"customer":"GM","assembly_flow":"Hercules","color_change_program":"D2LC"},
  {"style_code":264,"style_name":"D544 Front","pcs_per_carrier":3,"customer":"Ford","assembly_flow":"Reindeer","color_change_program":"D544"},
  {"style_code":258,"style_name":"D544 Front - New 4pc","pcs_per_carrier":4,"customer":"Ford","assembly_flow":"Reindeer","color_change_program":"D544"},
  {"style_code":263,"style_name":"D544 Rear","pcs_per_carrier":4,"customer":"Ford","assembly_flow":"Reindeer","color_change_program":"D544"},
  {"style_code":266,"style_name":"D544 Rocker LH","pcs_per_carrier":8,"customer":"Ford","assembly_flow":"Hercules","color_change_program":"D544"},
  {"style_code":265,"style_name":"D544 Rocker RH","pcs_per_carrier":8,"customer":"Ford","assembly_flow":"Hercules","color_change_program":"D544"},
  {"style_code":261,"style_name":"DS Rear LH 8c.","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":262,"style_name":"DS Rear RH 8c.","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":121,"style_name":"DS Heavy Duty LH","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":122,"style_name":"DS Heavy Duty RH","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":123,"style_name":"DS Light Duty LH","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":124,"style_name":"DS Light Duty RH","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":119,"style_name":"DS Heavy Duty LH TeePee","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":120,"style_name":"DS Heavy Duty RH Tee Pee","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":127,"style_name":"DS Light Duty LH TeePee","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":126,"style_name":"DS Light Duty RH TeePee","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"DS"},
  {"style_code":282,"style_name":"E2LB Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"E2LB"},
  {"style_code":283,"style_name":"E2LB_Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"E2LB"},
  {"style_code":285,"style_name":"E2LB Fog Bezel LH","pcs_per_carrier":24,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Black"},
  {"style_code":284,"style_name":"E2LB Fog Bezel RH","pcs_per_carrier":24,"customer":"GM","assembly_flow":"130 Area","color_change_program":"Black"},
  {"style_code":215,"style_name":"F391 Front Upper","pcs_per_carrier":4,"customer":"Ford","assembly_flow":"Reindeer","color_change_program":"391 MCA"},
  {"style_code":267,"style_name":"391 MCA Front","pcs_per_carrier":4,"customer":"Ford","assembly_flow":"Reindeer","color_change_program":"391 MCA"},
  {"style_code":268,"style_name":"391 MCA V6 Front","pcs_per_carrier":4,"customer":"Ford","assembly_flow":"Reindeer","color_change_program":"391 MCA"},
  {"style_code":249,"style_name":"391 MCA V6 Rear Valence","pcs_per_carrier":10,"customer":"Ford","assembly_flow":"Reindeer","color_change_program":"391 MCA"},
  {"style_code":269,"style_name":"391 MCA Fog Bezel RH","pcs_per_carrier":40,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"Black"},
  {"style_code":270,"style_name":"391 MCA Fog Bezel LH","pcs_per_carrier":40,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"Black"},
  {"style_code":235,"style_name":"HRDX Upper","pcs_per_carrier":8,"customer":"Honda","assembly_flow":"130 Area","color_change_program":"HRDX"},
  {"style_code":236,"style_name":"HRDX Lower","pcs_per_carrier":3,"customer":"Honda","assembly_flow":"130 Area","color_change_program":"HRDX"},
  {"style_code":69,"style_name":"JK Grill","pcs_per_carrier":9,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JK"},
  {"style_code":91,"style_name":"JK Grill TeePee","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JK"},
  {"style_code":74,"style_name":"JK Grill Dragon","pcs_per_carrier":9,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JKDragon"},
  {"style_code":173,"style_name":"JK Grill Dragon TeePee","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JKDragon"},
  {"style_code":320,"style_name":"JL Grille Sport","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":321,"style_name":"JL Grille Sahara","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":322,"style_name":"JL Applique RH","pcs_per_carrier":48,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":323,"style_name":"JL Applique LH","pcs_per_carrier":48,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":324,"style_name":"JL Grille Rings (set)","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":325,"style_name":"JL Grille Surround RH","pcs_per_carrier":56,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":326,"style_name":"JL Grille Surround LH","pcs_per_carrier":56,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":327,"style_name":"JL Grille Surround Ctr","pcs_per_carrier":48,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":328,"style_name":"JL Fog Bezel RH","pcs_per_carrier":48,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":329,"style_name":"JL Fog Bezel LH","pcs_per_carrier":48,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"JL"},
  {"style_code":201,"style_name":"KL1 Rear Upper RH","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"KL1"},
  {"style_code":202,"style_name":"KL1 Rear Upper LH","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"KL1"},
  {"style_code":203,"style_name":"KL1 Front Upper RH","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"KL1"},
  {"style_code":204,"style_name":"KL1 Front Upper LH","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"KL1"},
  {"style_code":205,"style_name":"KL1 Rear Valence SE","pcs_per_carrier":9,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"KL1/Dk. Neutral Mono"},
  {"style_code":213,"style_name":"KL1 Rear Valence DE","pcs_per_carrier":11,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"KL1/Dk. Neutral Mono"},
  {"style_code":206,"style_name":"KL1 Rear Hitch Cover","pcs_per_carrier":26,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"KL1/Dk. Neutral Mono"},
  {"style_code":297,"style_name":"KL2 Front Upper ","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"KL2"},
  {"style_code":207,"style_name":"KL2 Front Upper","pcs_per_carrier":4,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"KL2"},
  {"style_code":208,"style_name":"KL2 Rear Upper RH","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"KL2"},
  {"style_code":209,"style_name":"KL2 Rear Upper LH","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"KL2"},
  {"style_code":210,"style_name":"KL2 Rear Valence SE","pcs_per_carrier":11,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"KL2/Fine Silver"},
  {"style_code":211,"style_name":"KL2 Rear Valence DE","pcs_per_carrier":11,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Service"},
  {"style_code":212,"style_name":"KL2 Front Lower Applique","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"KL2/Fine Silver"},
  {"style_code":233,"style_name":"KL2 Rear Valance DE ET/MCE","pcs_per_carrier":11,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"KL2/Fine Silver"},
  {"style_code":259,"style_name":"KL2 Front Lower PTD","pcs_per_carrier":6,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"KL2 PTD"},
  {"style_code":260,"style_name":"KL2 Rear Lower PTD","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"KL2 PTD"},
  {"style_code":271,"style_name":"MP Front Onroad","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":272,"style_name":"MP Front Offroad Trailhawk","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":273,"style_name":"MP Upper Grille","pcs_per_carrier":12,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":274,"style_name":"MP Rear Upper","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":275,"style_name":"MP Rear Valence SE Onroad","pcs_per_carrier":11,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":276,"style_name":"MP Rear Valence HE Trailhawk","pcs_per_carrier":11,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":277,"style_name":"Hframe MP Fog Bezel Trim Ring LH - 1 Tray","pcs_per_carrier":15,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":278,"style_name":"Hframe MP Fog Bezel Trim Ring RH - 1 Tray","pcs_per_carrier":15,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":279,"style_name":"Hframe MP Center Grille Surround 1Tray","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":280,"style_name":"Hframe MP Lower Grille LH 1Tray","pcs_per_carrier":24,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":281,"style_name":"Hframe MP Lower Grille RH 1Tray","pcs_per_carrier":24,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"MP"},
  {"style_code":112,"style_name":"Nissan Rogue Liftgate","pcs_per_carrier":1,"customer":"Nissan","assembly_flow":"130 Area","color_change_program":"Nissan"},
  {"style_code":250,"style_name":"O1SL 17 Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"O1SL"},
  {"style_code":246,"style_name":"O1SL 16 Front","pcs_per_carrier":3,"customer":"GM","assembly_flow":"130 Area","color_change_program":"O1SL"},
  {"style_code":247,"style_name":"O1SL Rear","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"O1SL"},
  {"style_code":248,"style_name":"O1SL Rear Lower DE","pcs_per_carrier":10,"customer":"GM","assembly_flow":"130 Area","color_change_program":"O1SL"},
  {"style_code":227,"style_name":"RU Rocker LH","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"RU"},
  {"style_code":224,"style_name":"RU Rocker RH","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"RU"},
  {"style_code":218,"style_name":"S550_MCA_Front","pcs_per_carrier":3,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"S550"},
  {"style_code":219,"style_name":"S550 MCA Rear","pcs_per_carrier":4,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"S550"},
  {"style_code":null,"style_name":"S550 Base Front","pcs_per_carrier":3,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"S550"},
  {"style_code":null,"style_name":"S550 Base Rear ","pcs_per_carrier":3,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"S550"},
  {"style_code":null,"style_name":"S550 SVT Front","pcs_per_carrier":3,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"S550"},
  {"style_code":null,"style_name":"S550 SVT Rear","pcs_per_carrier":3,"customer":"Ford","assembly_flow":"130 Area","color_change_program":"S550"},
  {"style_code":87,"style_name":"SRT8_Rear_Cover_with_Hitch","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Black"},
  {"style_code":88,"style_name":"SRT8 Rear Cover without Hitch","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Black"},
  {"style_code":128,"style_name":"SRT8 Rear Lower","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Black"},
  {"style_code":198,"style_name":"SRT8_Rear_Upper","pcs_per_carrier":3,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"SRT8"},
  {"style_code":195,"style_name":"SRT8 Front LH","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"SRT8"},
  {"style_code":196,"style_name":"SRT8 Front RH","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"SRT8"},
  {"style_code":77,"style_name":"SRT8 Door LH","pcs_per_carrier":14,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"SRT8"},
  {"style_code":197,"style_name":"SRT8 Door RH","pcs_per_carrier":14,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"SRT8"},
  {"style_code":199,"style_name":"SRT8 Quarter Flares RH","pcs_per_carrier":14,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"SRT8"},
  {"style_code":214,"style_name":"SRT8 Quarter Flares LH","pcs_per_carrier":14,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"SRT8"},
  {"style_code":138,"style_name":"SRT8 Rocker LH","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"SRT8"},
  {"style_code":137,"style_name":"SRT8 Rocker RH","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"SRT8"},
  {"style_code":293,"style_name":"T300 MCM Front RS","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"T300 MCM"},
  {"style_code":294,"style_name":"T300 MCM Hatchback RS","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"T300 MCM"},
  {"style_code":290,"style_name":"T300 MCM Front Base","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"T300 MCM"},
  {"style_code":291,"style_name":"T300 MCM Rear NB","pcs_per_carrier":4,"customer":"GM","assembly_flow":"130 Area","color_change_program":"T300 MCM"},
  {"style_code":292,"style_name":"T300 MCM RS Rear Lower Notchback","pcs_per_carrier":10,"customer":"GM","assembly_flow":"130 Area","color_change_program":"T300 MCM"},
  {"style_code":193,"style_name":"WK14 Rear Lower","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"WK"},
  {"style_code":54,"style_name":"WK_Rear","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"WK"},
  {"style_code":301,"style_name":"WK16.5 Front Upper","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"WK"},
  {"style_code":302,"style_name":"WK16.5 Front Lower Masked","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"WK"},
  {"style_code":306,"style_name":"WK17 Trackhawk Front Upper Grille","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Black"},
  {"style_code":307,"style_name":"WK17 Trackhawk Front","pcs_per_carrier":3,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"SRT8"},
  {"style_code":308,"style_name":"WK17 Trackhawk Center Applique","pcs_per_carrier":20,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Black"},
  {"style_code":309,"style_name":"WK17 Trackhawk Front Lower Applique","pcs_per_carrier":20,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Black"},
  {"style_code":299,"style_name":"WK16.5 Rear Lower SE","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"WK"},
  {"style_code":310,"style_name":"WK16.5 Grille","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"Black"},
  {"style_code":303,"style_name":"WK16.5 Grille","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"Black"},
  {"style_code":316,"style_name":"WK18 Hellcat RH Fog Bezel","pcs_per_carrier":24,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":""},
  {"style_code":317,"style_name":"WK18 Hellcat LH Fog Bezel","pcs_per_carrier":24,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":""},
  {"style_code":318,"style_name":"WK18 Hellcat Rear Lower","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":""},
  {"style_code":319,"style_name":"WK18 Hellcat Hitch Cover","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":""},
  {"style_code":287,"style_name":"WD14_16_FL","pcs_per_carrier":9,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"WD"},
  {"style_code":289,"style_name":"WD14_16_RL","pcs_per_carrier":9,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"WD"},
  {"style_code":231,"style_name":"WD14 Hitch Cover-NTow","pcs_per_carrier":20,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"WD"},
  {"style_code":220,"style_name":"WD14 Hitch Cover-Tow","pcs_per_carrier":20,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"WD"},
  {"style_code":234,"style_name":"WD14 Front Upper","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"WD"},
  {"style_code":117,"style_name":"WD14 Front Upper","pcs_per_carrier":4,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"WD"},
  {"style_code":225,"style_name":"WD_Rear_Upper","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"WD"},
  {"style_code":129,"style_name":"WD_Rear_Upper","pcs_per_carrier":4,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"WD"},
  {"style_code":314,"style_name":"WD18 SRT8 Rear Lower","pcs_per_carrier":9,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":""},
  {"style_code":315,"style_name":"WD18 SRT8 Front","pcs_per_carrier":3,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":""},
  {"style_code":136,"style_name":"WK14 Summit Rear Upper","pcs_per_carrier":5,"customer":"Chrysler","assembly_flow":"130 Area","color_change_program":"Summit"},
  {"style_code":304,"style_name":"WK17 Summit Front Upper Masked","pcs_per_carrier":4,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Summit"},
  {"style_code":305,"style_name":"WK17 Summit Front Lower","pcs_per_carrier":10,"customer":"Chrysler","assembly_flow":"Reindeer","color_change_program":"Summit"},
  {"style_code":178,"style_name":"Summit_Hitch_Cover","pcs_per_carrier":16,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"Summit"},
  {"style_code":194,"style_name":"WK14 Summit Rear Lower","pcs_per_carrier":8,"customer":"Chrysler","assembly_flow":"Hercules","color_change_program":"Summit"}
]

module.exports = styleCodes;
